<font color="">**Learning Python at University of Glasgow**</font>

<font color="">**NumPy (Numerical Python): To make Python feel like MATLAB**</font>

<font color="DeepSkyBlue">**Lecturer**</font>: **Khiem Nguyen**

# NumPy

## First few words about **NumPy**

***
**NumPy** (Numerical Python) is open source Python library that's used in almost every field of science and engineering. It's the universal standard for working with numerical data in Python, and it's at the core of the scientific Python and PyData ecosystems. By PyData, it refers to a branch of application of Python in Data Science. NumPy users include everyone from beginning coders to experienced researchers doing state-of-the-art scientific and industrial research and development. The NumPy API is used extensively in Pandas, SciPy, Matplotlib, scikit-learn, scikit-image and most other data science and scientific Python packages.

The **NumPy** library contains multi-dimensional array and matrix data structures (you'll find more information about this later). It provides `ndarray`, a homogeneous n-dimensional array object, with methods to efficiently operate on it. NumPy can be used to perform a wide variety of mathematical operations on arrays. It adds powerful data structures to Python that guarantee efficient calculations with arrays and matrices and it supplies an enormous library of high-level mathematical functions that operate on these arrays and matrices.

***
**Installing NumPy**

If you run the command line `import numpy as np` with error, it is very likely that you have not installed NumPy package. You can install NumPy using the Anaconda CMD prompt or Anaconda with the command
```Python
conda install numpy
```
or directly using the Jupyter Notebook with the command
```Python
pip install numpy
```

***
**How to import Numpy**
You have already used it for some time. But it is good to repeat

```Python
import numpy as np
```
We shorten the imported name to `np` for better readability of code using NumPy. This is widely adopted convention that you should follow so that anyone working with your code can easily understand it.

***
**What's the difference between a Python list and a NumPy array**?

NumPy gives you an enormous range of fast and efficient ways of creating arrays and manipulating numerical data inside them. While a Python list can contain different data types within a single list, all of the elements in a NumPy array should be homogeneous. The mathematical operations that are meant to be performed on arrays would be extremely inefficient if the arrays weren’t homogeneous.

**Why use NumPy?** &nbsp; NumPy arrays are faster and more compact than Python lists. An array consumes less memory and is convenient to use. NumPy uses much less memory to store data and it provides a mechanism of specifying the data types. This allows the code to be optimized even further.

In [1]:
# Installation
# Uncomment the line to install numpy in case it is not installed before.
# pip install numpy

# import the library. The community agree on the alias "np" for the namespace representing the library NumPy

import numpy as np      

## <font color='DeepSkyBlue'> Array in NumPy </font>

### What is an array?

An array is a central data structure of the NumPy library. An array is a grid of values and it contains information about the raw data, how to locate an element, and how to interpret an element. It has a grid of elements that can be indexed in various ways. The elements are all of the same type, referred to as the array `dtype`.

An array can be indexed by a tuple of non-negative integers, by booleans, by another array, or by integers. The rank of the array is the number of dimensions. The shape of the array is a tuple of integers giving the size of the array along each dimension.

**Example by illustration**

In the following figure, we present three 3-dimensional arrays of the same size $(3, 4, 5)$. All three arrays has in total $3 \times 4 \times 5 = 60$ components and are created by commands defined in NumPy library. there are $3$

<img src="./figures/numpy_illustration.png" width=600/>

### How to create a basic array

This section covers
  1. `np.array()`
  2. `np.zeros()`
  3. `np.ones()`
  4. `np.empty()`
  5. `np.arange()`
  6. `np.linspace()`
  7. `dtype`
***
To create a NumPy array, we can use the function `np.array()`. All we need to do to create a simple array is pass a list to `np.array()`. We can also specify the type of data in the list.

We can create an array filled with zeros by `np.zeros()`, or an array filled with 1's by `np.ones()`, or even an empty array with `np.empty()`. The function `np.empty()` creates an array whose initial content is random and depends on the state of the memory. The reason to use `np.empty()` over `np.zeros()` (or something similar) is speed - just make sure to fill every element afterwards. 

We can create an array with a range of elements using `np.arange()`, just like `range()` function of Python. However, `np.arange()` allows non-integer step size. WE can also use `np.linspace()` to create an array with values that spaced linearly in a specified interval.

**Specifying data type**

While the default data type is floating point, i.e. `np.float64`, we can explicitly specify which data type we want using the `dtype` keyword.

**Best by examples**

In [2]:
import numpy as np  # First of all for using numpy

In [3]:
np.einsum?

Signature:       np.einsum(*operands, out=None, optimize=False, **kwargs)
Call signature:  np.einsum(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function einsum at 0x0000022B85ACC7C0>
File:            c:\users\ln69g\appdata\local\anaconda3\lib\site-packages\numpy\core\einsumfunc.py
Docstring:      
einsum(subscripts, *operands, out=None, dtype=None, order='K',
       casting='safe', optimize=False)

Evaluates the Einstein summation convention on the operands.

Using the Einstein summation convention, many common multi-dimensional,
linear algebraic array operations can be represented in a simple fashion.
In *implicit* mode `einsum` computes these values.

In *explicit* mode, `einsum` provides further flexibility to compute
other array operations that might not be considered classical Einstein
summation operations, by disabling, or forcing summation over specified
subscript labels.

See the notes and examples for clarification.

Parameters
----------
subs

In [4]:
a = np.array([1, 2, 3])         # create an array of 3 elements 1, 2, 3
print(a)                        # note the output difference between print(a) and a
a

[1 2 3]


array([1, 2, 3])

In [5]:
b = np.array([[1, 2], [3, 4]])  # create a matrix of size (2 x 2)
print(b)                        # note the output difference between print(b) and b
print(repr(b))

[[1 2]
 [3 4]]
array([[1, 2],
       [3, 4]])


**Visualization for your brain**

<img src="./figures/create-numpy-array-1.png" height="150"/> &nbsp; <img src="./figures/create-numpy-array-2d.png" height="150"/>

**Why output difference between with and without** `print()`

This difference has the deep root related to how an object of a particular data type will be shown on the output console for viewing. We will discuss this topic in the next point. For now, at least you can notice that while using `print()` the output is readable to human level but we don't know exactly whether the output is just simply string or a `ndarray` object. In contrast, without using `print()` we know that the output is clearly an object of class `ndarray`.

In the following, we use `print()` to see the outputs to avoid writing codes in many block of codes with just two lines. For example, to see the `ndarray` representation, we use
```Python
x = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
x           # without print()
```
for one block of code.

In [6]:
array_zeros = np.zeros(2)
array_ones = np.ones(2)
array_empty = np.empty(2)               

print("array_zeros =", array_zeros)
print("array_ones  =", array_ones)
print("array_empty =", array_empty)   # may vary in different runs

array_zeros = [0. 0.]
array_ones  = [1. 1.]
array_empty = [5.29371929e+180 9.75023779e+199]


In [7]:
np.zeros?

Docstring:
zeros(shape, dtype=float, order='C', *, like=None)

Return a new array of given shape and type, filled with zeros.

Parameters
----------
shape : int or tuple of ints
    Shape of the new array, e.g., ``(2, 3)`` or ``2``.
dtype : data-type, optional
    The desired data-type for the array, e.g., `numpy.int8`.  Default is
    `numpy.float64`.
order : {'C', 'F'}, optional, default: 'C'
    Whether to store multi-dimensional data in row-major
    (C-style) or column-major (Fortran-style) order in
    memory.
like : array_like, optional
    Reference object to allow the creation of arrays which are not
    NumPy arrays. If an array-like passed in as ``like`` supports
    the ``__array_function__`` protocol, the result will be defined
    by it. In this case, it ensures the creation of an array object
    compatible with that passed in via this argument.

    .. versionadded:: 1.20.0

Returns
-------
out : ndarray
    Array of zeros with the given shape, dtype, and order.

See Al

In [8]:
zeros_2D = np.zeros((2, 3))     # input of a tuple
print(zeros_2D)
b = np.zeros( (2, 3), dtype=np.int16 )

[[0. 0. 0.]
 [0. 0. 0.]]


In [9]:
print()

In [10]:
a = np.arange(4) # integers only --> array of 0, 1, 2, 3 jus like range() function
b = np.arange(2, 9, 1.5)     # first number = 2, last number = 15, step size = 1.5
c = np.linspace(0, 10, num=5)   # 5 numbers 0 --> 10 evenly distanced 
print("a =", a)
print("b =", b)
print("c =", c)

a = [0 1 2 3]
b = [2.  3.5 5.  6.5 8. ]
c = [ 0.   2.5  5.   7.5 10. ]


In [11]:
x = np.ones((2, 4), dtype=np.int64)
print(x)    # The output does not tell use the data type of elements in the array
x           # This tell us exactly what is happening, an ndarray with element data type is int64

[[1 1 1 1]
 [1 1 1 1]]


array([[1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int64)

### Deeper Understanding: **`repr()` versus `str()`**

Essentially, NumPy array is a data type of class `ndarray` and thus it has the so-called builtin function name `__repr()__` that is defined to show the representation of the object. On the other hand, the builtin function name `__str()__ ` is used to show readable output. When we don't pass the `ndarray` to the function `print()` and just type out the variable name, this is equivalent to pass the variable to the function `repr()`. In this case, the representation of an `ndarray` will be shown on the output console. On the other hand, by by passing the `ndarray` to function `print()`, the output is for end user to read it. In this case, the statement `print(x)` is equivalent to `str(x)`.

**Summary**

`str()` is used for creating output for end user while `repr()` is mainly used for debugging and development, `repr()`'s goal is to be *ungmbiguous* and `str()`'s is to be readable. For example, if we suspect a float has a small rounding error, `repr()` will show us while `str()` may not.

**Best by examples**

In [12]:
class PrintOut:
    """Test difference between __str__() and __repr__()"""
    def __init__(self, data):
        self.data = data
        
    def __str__(self):
        print("Inside __str__:")
        return str(self.data)
    
    def __repr__(self):
        print("Inside __repr__:")
        return repr(self.data)

# External to the class
test = PrintOut("a text line")

In [13]:
# The following statements give the same effect:
print(test)
print()
print(str(test))

Inside __str__:
a text line

Inside __str__:
a text line


In [14]:
# However, repr() tells us that the output is a string (not just something we can read)
print(repr(test))

Inside __repr__:
'a text line'


In [15]:
test

Inside __repr__:


'a text line'

### Create an array from existing data: vertical stack and horizontal stack - view and copy

Sometimes, we also want to join multiple matrices in a specific manner to have a bigger matrix. In a more general sense, we can do this for higher-dimensional array, i.e., we can combine multiple high-dimensional arrays in an appropriate fashion. For example, let us assume $\mathbf{A}$ and $\mathbf{B}$ are two matrices of shape $(2 \times 2)$. Then, we can stack or combine $\mathbf{A}$ and $\mathbf{B}$ horizontally to have a new matrix of shape $(4 \times 2)$ or vertically to have obtain the matrix of shape $(2 \times 4)$. However, clearly we cannot stack two matrices of shape $(2 \times 2)$ and $(4\times 2)$ horizontally but we can combine them vertically to obtain the new matrix of shape $(6 \times 2)$.

**Remark**

In this notebook, I normally write the matrix of shape $(m \times n)$ or of size $(m \times n)$ in the mathematical sense to mean that the matrix has $m$ rows and $n$ columns. In mathematics, we read the matrix of size $m$-by-$n$, denoeted as $(m \times n)$.

In NumPy, the shape of the considered array is given by a tuple `(m, n)` meaning that the array has `m` elements in the 1st dimension and `n` elements along the 2nd dimension. In fact, I can write the matrix $\mathbf{A}$ of shape $(m, n)$ in the mathematical sense but this is a bit unconventional in the mathematic community.

***
This sub-section covers and
  1. `np.vstack()`
  2. `np.hstack()`
  3. `.view()`
  4. `copy()`
***
We can stack two existing arrays, both vertically and horizontally by using `np.vstack()` and `np.hstack()`. 
  
We can use the `view()` method to create a new array object that looks at the same data as the original array (a **shallow copy**). Views are an important NumPy concept. NumPy functions, as well as operations like indexing and slicing, will return views whenever posible. This saves memory and is faster (no copy of the data has to be made). However, it's important to be award of this -- modifying data in a view also modifies the original array. Using the copy method will make a complete copy of the array and its data (**deep copy**)

**Best by examples**

In [16]:
# Let us define two arrays
a1 = np.array([[1, 1], [2, 2]])
a2 = np.array([[3, 3], [4, 4]])

a_vstack = np.vstack((a1, a2))
print("a_vstack =\n", a_vstack)
print("--------------------")
a_hstack = np.hstack((a1, a2))
print("a_hstack =\n", a_hstack)

a_vstack =
 [[1 1]
 [2 2]
 [3 3]
 [4 4]]
--------------------
a_hstack =
 [[1 1 3 3]
 [2 2 4 4]]


In [17]:
# Let us define an array 
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print("a =\n", a)
# Now, we create an array b1 by slicing and modifying the first element of b1.
b1 = a[0, :]    # the first row of a
print("b1 =\n",b1)

b1[0] = 99      # now, we modify the first element of b1
print("b1 =\n",b1)

# Let us re-examine the array ar
print("a =\n", a)
# You should see the array has changed according the changes in b1

a =
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
b1 =
 [1 2 3 4]
b1 =
 [99  2  3  4]
a =
 [[99  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [18]:
# Using the copy method will make a complete copy of the array and its data.
b2 = a.copy()
b2[0,0] = 0
print("a =\n", a)
print("b2 =\n", b2)

a =
 [[99  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
b2 =
 [[ 0  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


## <font color='DeepSkyBlue'> Dimension, size and shape of an array and reshape arrays </font>

As seen above, we can create one-dimensinoal arrays and multi-dimensional arrays. Very often, we want to work with the same set of numbers or elements but it is more convenient to visualize the set in different shapes. For example, a 3D vector in mathematics consists of three numbers but we can visualize it as a column vector or a row vector. The column vector and the row vector are example of two-dimensional arrays of different shapes; $(n \times 1)$ for the column vector of $n$ elements and $(1 \times n)$ for the row vector $n$ elements. Clearly, the $n$-dimensional vector in the mathematical sense has $n$ elements regardless how we want to visualize it. Thus, it is important to know the number of dimensions of an array, how to transform an array into different arrays of different sizes but with the same number elements. The object of type `ndarray` is equipped with many attributes and methods to query the number of dimensions, reshaping the array. This will be the topic of this section.

### Dimension, shape and size 
This sub-section covers
  1. `ndarray.ndim`
  2. `ndarray.shape`
  3. `ndarray.size`

As mentioned, `ndarray` is a class and one particular object of this class data type have attributes and methods. In the above list, we see some common attributes of `ndarray`.

- `ndarray.ndim` will tell us the number of axes, or dimensions, of the array
- `ndarray.shape` will display a tuple of integers that indicate the number of elements stored along each dimension of the array. If, for example, we have a 2-D array with 2 rows and 3 columns, the shape of the array is `(2, 3)`.
- `ndarray.size` will tell us the total number of elements of the array. This is essentially the *product* of the elements of the array's shape

**Remark**

In this notebook, I normally write the matrix of shape $(m \times n)$ or of size $(m \times n)$ in the mathematical sense to mean that the matrix has $m$ rows and $n$ columns. In mathematics, we read the matrix of shape/size $m$-by-$n$. 

In NumPy, the shape of the considered array is given by a tuple `(m, n)` meaning that the array has `m` elements in the 1st dimension and `n` elements along the 2nd dimension. In fact, I can write the matrix $\mathbf{A}$ of shape $(m, n)$ in the mathematical sense but this is a bit unconventional in the mathematic community.

**Best by examples**

In [19]:
array_2d = np.array([[1, 2, 3], 
                     [4, 5, 6]])

print("ndim  =", array_2d.ndim)
print("shape =", array_2d.shape)    # the shape should be (2, 3)
print("size  =", array_2d.size)     # number of elements in the array

ndim  = 2
shape = (2, 3)
size  = 6


In [20]:
array_3d = np.array([[[0, 1, 2, 3],
                      [4, 5, 6, 7]],
                           
                      [[0, 1, 2, 3],
                       [4, 5, 6, 7]],
                           
                      [[0, 1, 2, 3],
                       [4, 5, 6, 7]]])

print("ndim  =", array_3d.ndim)
print("size  =", array_3d.size)
print("shape =", array_3d.shape)

ndim  = 3
size  = 24
shape = (3, 2, 4)


In [21]:
array_3d[0, 0]

array([0, 1, 2, 3])

In [22]:
array_3d_shape = array_3d.shape
print(np.prod(array_3d))     # product of all elements in the tuple (3, 2, 4)

0


In [23]:
array_4d = array_3d.reshape((3, 2, 2, 2))       # we will talk about reshape later
print(array_4d)

print("ndim  =", array_4d.ndim)
print("size  =", array_4d.size)
print("shape =", array_4d.shape)   


[[[[0 1]
   [2 3]]

  [[4 5]
   [6 7]]]


 [[[0 1]
   [2 3]]

  [[4 5]
   [6 7]]]


 [[[0 1]
   [2 3]]

  [[4 5]
   [6 7]]]]
ndim  = 4
size  = 24
shape = (3, 2, 2, 2)


### Adding, removing, and sorting elements

This section covers
  1. `np.sort()`
  2. `np.concatenate()`
***
Sorting an element is done with `np.sort()`. We can specify the axis, kind and order when we call the function. To read more about sorting an array, follow the link [numpy.sort](https://numpy.org/doc/stable/reference/generated/numpy.sort.html#numpy.sort)

We can concatenate arrays by sepcific dimension. It would very easy to concatenate two one-dimensional arrays becase we have only choice to do so. The array $[1, 2, 3]$ connected with $[4, 5]$ would give $[1, 2, 3, 4, 5]$. However, if we have, for example,
$$ \mathbf{A} = \begin{bmatrix} 1 & 2 \\ 3 & 4\end{bmatrix} \quad \mathbf{B} = \begin{bmatrix} 5 & 6 \\ 7 & 8 \end{bmatrix}$$
then we can connect them in two ways: put $\mathbf{B}$ (1) along the column of $\mathbf{A}$ to have
$$ \mathbf{C} = \begin{bmatrix} 1 & 2 \\ 3 & 4 \\ 5 & 6 \\ 7 & 8\end{bmatrix}$$
 or (2) along the row of $\mathbf{A}$ to get
$$ \mathbf{D} = \begin{bmatrix} 1 & 2 & 5 & 6\\ 3 & 4 & 7 & 8 \end{bmatrix}$$

To concatenate along a specific dimension, we use the keyword argument `axis=` of the function `np.concatenate()`. In this example, assuming that `a` and `b` defining the two matrices $\mathbf{A}$ and $\mathbf{B}$, respectively, then we can concatenate them along the `axis=0` for matrix $\mathbf{C}$ or along the `axis=1` for matrix $\mathbf{D}$. 

**Note** &nbsp; To understand why `axis=0` and `axis=1`, we will need more a bit of knowledge concerning indexing. However, you can guess for now that `axis=0` means along the row or along the first dimension, `axis=1` means along the column or along the second dimension. As the convention indexing in Python is to count from *zero*, the first dimension would correspond to `0` and the second dimension to `1` and so on.

Please be patient until everything makes sense in the end.

**Best by examples**

In [24]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])    # let us start with the array
np.sort(arr)                                # sort the numbers in ascending order (by default)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [25]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
# We can concatenate the two arrays by
np.concatenate((a, b))  # note the tuple (a, b)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [26]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
c = np.concatenate((a, b), axis=0)
d = np.concatenate((a, b), axis=1)
print("c =", repr(c))
print("d =", repr(d))

c = array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])
d = array([[1, 2, 5, 6],
       [3, 4, 7, 8]])


### Reshape an array

**Using** `arr.reshape()`

Using `arr.reshape()`, where `arr` is an `ndarray` object, will give a new shape to an array without chaning the data. Just remember that when we use the reshape method, the array we want to produce needs to have **the same number of elements as the original array**. 

If we start with an array with 12 elements, we'll need to make sure that our new aray also há a total of 12 elements. For example, a 1-D array of 12 elements can be reshaped to 2-Darray, namely a matrix, of shape $(2 \times 6)$, $(3 \times 4)$ or $(4 \times 3)$, or even to a 3-D array of shape $(2 \times 3  \times 2)$ and so on.

**Using** `np.reshape()`

With `np.reshape`, we can specify a few optional parameters:

```Python
np.reshape(arr, newshape=value, order='C')
```
  - `newshape` is the new shape we want. We can specify an integer or a tuple of integers. If we specify an integer, the result will be an array of that length. Again, the shape should be compatible with the original shape.
  - `order`: `'C'` means to read/write the elements using C-like index order, `'F'` means to read/write the elements using Fortran-like index order, `'A'` means to read/write the elements in Fortran-like index order if a is Fortran contiguous in memory, C-like order otherwise. (This is an optional parameter and doesn’t need to be specified.)

**Column-major language** vs **Row-major language**

If you wan to learn more about C and Fortran order [read more about the internal organization of NumPy arrays here](https://numpy.org/doc/stable/dev/internals.html#numpy-internals). Essentially, C and Fortran orders have to do with how indices correspond to the order the array is stored in memory. In Fortran, when moving through the elements of a two-dimensional array as it is stored in memory, the first index is the most rapidly varying index. As the first index moves to the next row as it changes, the matrix is stored one column at a time. This is why Fortran is thought of as a **Column-major** language. In C on the other hand, the last index changes the most rapidly. The matrix is stored by rows, making it a **Row-major** language. What you do for C or Fortran depends on whether it’s more important to preserve the indexing convention or not reorder the data.

**Best by examples**

In [27]:
a = np.arange(12)
print("a =\n", repr(a))
b1 = a.reshape(3, 4)    # reshape a into a matrix, b1 is a matrix now
b2 = b1.transpose()     # transpose of matrix b1
b3 = a.reshape(2, 6)    # just another matrix of size (2 x 6)
print("b1 =\n", repr(b1))
print("b2 =\n", repr(b2))
print("b3 =\n", repr(b3))
c = a.reshape(2, 3, 2)  # 3-D array
print("c =\n", repr(c))

a =
 array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
b1 =
 array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])
b2 =
 array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])
b3 =
 array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])
c =
 array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])


In [28]:
# We can use np.reshape() with similar effect
np.reshape(a, newshape=(3, 4), order='C')   # of course, a is the array to be reshaped

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

### Add new axis to an array

We can use `np.newaxis` and `np.expand_dims()` to increase the dimensions of our existing array. We probably do not see the real application of such an action yet for now but this make sense when we continue.

Using `np.newaxis` will increase the dimensions of your array by one dimension when used once. This means that 1D array will become 2D array, a 2D array will become a 3D array, and so on.

We can also expand an array by insert a new axis at a specified position with `np.expand_dims()` using the Syntax
```Python
new_array = np.expand_dims(arr, axis=integer_value)
```
So `np.expand_dims()` works more generally than `np.newaxis`.

**Best by example**

If we define an array by 
```Python
a = np.arange(6)
a.shape
```
we will see that `a.shape` returns `(6,)` instead of `(6, 1)` or `(1, 6)`. From a mathematical point of view, we can interpret $\mathbf{a} = (0, 1, 2, 3, 4, 5)$ represented by the variable `a` as a vector while the row vector 
$$\begin{bmatrix} 0 & 1 & 2 & 3 & 4 & 5\end{bmatrix}$$
is a matrix, or 2D array, of the size (1, 6)
and the column vector
$$\begin{bmatrix} 0 \\ 1 \\ 2 \\ 3 \\ 4 \\ 5 \end{bmatrix}$$
is a matrix, or 2D array, of the size (6, 1). Clearly, a vector could be understood as either a row vector or a column vector as it represents an entity of 6-dimension rather than how it should be represnted. So, create a column vector or a row vector out of a mathematical vector, we need to add one more dimension, or new axis in the language of NumPy, to the mathematical vector to make up a matrix which has size of 1 in either the first dimension (column vector) or in the second dimension (row vector).

In [29]:
a = np.arange(6)
print("a =\n", repr(a))
print("a.shape =", a.shape)

a =
 array([0, 1, 2, 3, 4, 5])
a.shape = (6,)


In [30]:
# To create a row vector, we insert an axis along the first dimension
a_row = a[np.newaxis, :]
print("a_row =\n", repr(a_row))
print("a_row.shape =", a_row.shape)

a_row =
 array([[0, 1, 2, 3, 4, 5]])
a_row.shape = (1, 6)


In [31]:
# To have a column vector, we insert an axis along the second dimension
a_column = a[:, np.newaxis]
print("a_column =\n", repr(a_column))
print("a_column.shape =", a_column.shape)

a_column =
 array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])
a_column.shape = (6, 1)


In [32]:
# We can use np.expand_dims to add an axis at index position 0 or 1 to create a row vector or a column vector, just like using np.newaxis before
row_vector = np.expand_dims(a, axis=0)
print("row_vector =\n", repr(row_vector))

column_vector = np.expand_dims(a, axis=1)
print("column_vector =\n", repr(column_vector))

row_vector =
 array([[0, 1, 2, 3, 4, 5]])
column_vector =
 array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])


### Reshaping and flattening multi-dimensional arrays

There are two popular ways to flatten arrays:
- `arr.flatten()`
- `arr.ravel()`

The primary difference between the two is that the new array created using `ravel()` is actually reference to the parent array, i.e. a __view__. This means that any changes to the new array will affect the parent array as well. Since `ravel()` does not create a copy, it's memory efficient.

In [33]:
x = np.array([[1, 2, 3, 4], 
              [5, 6, 7, 8], 
              [9, 10, 11, 12]])
# When we use flatten(), changes to your new array won't change 
# the parent array.
a1 = x.flatten()
a1[0] = 999
print("x =\n", x)
print("a1 =\n", a1)

x =
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
a1 =
 [999   2   3   4   5   6   7   8   9  10  11  12]


In [34]:
x = np.array([[1, 2, 3, 4], 
              [5, 6, 7, 8], 
              [9, 10, 11, 12]])
# But when we use ravel(), the changes we make to the new array will affect the parent array.
a2 = x.ravel()
a2[0] = 999
print("Array after ravelling:\n", a2, "\n")

print("Original array before raveling:\n", x)

Array after ravelling:
 [999   2   3   4   5   6   7   8   9  10  11  12] 

Original array before raveling:
 [[999   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


Learn how to read documentation

In [35]:
np.array?

Docstring:
array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
      like=None)

Create an array.

Parameters
----------
object : array_like
    An array, any object exposing the array interface, an object whose
    ``__array__`` method returns an array, or any (nested) sequence.
    If object is a scalar, a 0-dimensional array containing object is
    returned.
dtype : data-type, optional
    The desired data-type for the array. If not given, NumPy will try to use
    a default ``dtype`` that can represent the values (by applying promotion
    rules when necessary.)
copy : bool, optional
    If true (default), then the object is copied.  Otherwise, a copy will
    only be made if ``__array__`` returns a copy, if obj is a nested
    sequence, or if a copy is needed to satisfy any of the other
    requirements (``dtype``, ``order``, etc.).
order : {'K', 'A', 'C', 'F'}, optional
    Specify the memory layout of the array. If object is not an array, the
    newly crea

In [36]:
a = np.array([[1, 2, 3], [4, 5, 6]])
np.sum?

Signature:      
np.sum(
    a,
    axis=None,
    dtype=None,
    out=None,
    keepdims=<no value>,
    initial=<no value>,
    where=<no value>,
)
Call signature:  np.sum(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function sum at 0x0000022B85A37EC0>
File:            c:\users\ln69g\appdata\local\anaconda3\lib\site-packages\numpy\core\fromnumeric.py
Docstring:      
Sum of array elements over a given axis.

Parameters
----------
a : array_like
    Elements to sum.
axis : None or int or tuple of ints, optional
    Axis or axes along which a sum is performed.  The default,
    axis=None, will sum all of the elements of the input array.  If
    axis is negative it counts from the last to the first axis.

    .. versionadded:: 1.7.0

    If axis is a tuple of ints, a sum is performed on all of the axes
    specified in the tuple instead of a single axis or all the axes as
    before.
dtype : dtype, optional
    The type of the returned array and of the ac

## <font color='DeepSkyBlue'> Access elements of array </font>

**A short summary first** &nbsp; We can **index** and **slice** and slice NumPy arrays in the same ways we can slide Python lists. However, there is more than just that 😋

### Indexing and slicing

**A short summary first** &nbsp; We can **index** and **slice** and slice NumPy arrays in the same ways we can slide Python lists. 

We may want to take a section of our array or specific array elements to use in further analysis or additional operations. To do that, we'll need to subset, slice, and/or index our arrays.

In [37]:
data = np.arange(3)
print("data = ", data)
print("data[1] =\n", repr(data[1]))
print("data[0:2] =\n", repr(data[0:2]))
print("data[-2:] =\n", repr(data[-2:]))

data =  [0 1 2]
data[1] =
 1
data[0:2] =
 array([0, 1])
data[-2:] =
 array([1, 2])


In [38]:
array_2d = np.array([[1, 2], [3, 4], [5, 6]])
print("array_2d[0,:] =", array_2d[0,:])
print("array_2d[:,0] =", array_2d[0,:])

array_2d[0,:] = [1 2]
array_2d[:,0] = [1 2]


In [39]:
# Print all the elements along the first axis
for i in range(array_2d.shape[0]):
    print(array_2d[i,])
    
# Print all the elements along the second axis
for i in range(array_2d.shape[1]):
    print(array_2d[:,i])


[1 2]
[3 4]
[5 6]
[1 3 5]
[2 4 6]


<img src="./figures/indexing-and-slicing-in-ndarray.png" width="750"/>

### Selection with conditions

If we want to select values from the array that fulfill certain conditions, it's super straightforward with NumPy.

Essentially, the key idea in selection process, the statement involving a condition will return an array of the same size as the original array with the Boolean values `True` and `False`. What happens is that the condition will be evaluated in the element-wise fashion, i.e., for each element of the array. Then, we receive the new array in which the values `True` correspond to the elements that fulfill the condition, or the values `False` otherwise. This new array holding only Boolean values will act like a masking array telling the original array which element should be picked up. Only elements corresponding to the `True` of the masking array are chosen.

For example, if we have the array
```Python
a = np.array([1, 2, 3, 4, 5])
```
Then, the statement 
```Python 
masking_array = (a >= 2 and a <= 4)
``` 
will return
```Python
masking_array = np.array([False, True, True, True, False])
```
This masking array is then used as a special slicing for the `ndarray` variable `a` so that we can write `a[masking_array]` legally. Then, as expected, `a[masking_array]` should give us the new array that picking up only values `2`, `3`, and `4`. Following this explanation, we can conclude, for example `a[[True, False, False, False, True]]` would return `np.array([1, 3, 5])`.

In [40]:
a = np.arange(6)
print("a[a < 5] =", repr(a[a < 5]))
# What truely happens is as follows
print("Under the hood:\n------------")
masking = a < 3
print("masking =", repr(masking))
b = a[masking]
print("b = a[masking] =", repr(b))

a[a < 5] = array([0, 1, 2, 3, 4])
Under the hood:
------------
masking = array([ True,  True,  True, False, False, False])
b = a[masking] = array([0, 1, 2])


In [41]:
a = np.arange(1, 6, 1)
a[[True, False, True, False, True]]

array([1, 3, 5])

## Operations on ndarray

### Basic operations: element-by-element calculation

Once we've created our arrays, we can start to work with them. One of the most basic things to remember when dealing with NumPy array is that most of the mathematical operations such as addition, subtraction, multiplication, division and so on are working on the element-by-element basis. Assume that $\otimes$ is an operation acting on two NumPy array `a` and `b` of shape $(n_0, n_1, \ldots, n_M)$, denoted mathematically hereby as $\mathbf{A}$ and $\mathbf{B}$. The operation symbol $\otimes$ is just a symbol that may represent the addition $+$, the subtraction $-$, the multiplication $\ast$ and the division $/$.

Then, the result array $\mathbf{c} = \mathbf{a} \otimes \mathbf{b}$ are computed according to
$$
c[i_0][i_1]...[i_{M}] = a[i_0][i_1]...[i_M] \otimes b[i_0][i_1]...[i_M]
$$
where $[...]$ refers to probably extra running index in the array $\mathbf{a}$ and $\mathbf{b}$ and the indices $i_1, i_2, \ldots, i_M$ running in the valid ranges.

**Example**
Assume that `a` and `b` are two arrays of shape `(3, 4)`, the expression `c = a + b` will be evaluated by adding each element in `a` to the corresponding element in `b` with the same index position. For example, if `a` and `b` are two matrices, then `a[0][0]` will be added to `b[0][0]` and assigned to `c[0][0]`, `a[0][1]` added to `b[0][1]` and assigned to `c[0][1]` and so on. Thus, we have the following pattern
```Python
c[i][j] = a[i][j] + b[i][j]
```
for all running valid indices `i` (from $0$ to $2$) and `j` (from $0$ to $3$) of the array `a` and `b`. Similarly, the subtraction, multiplication and division between two NumPy arrays of the same shape are performed on the element-by-element basis.

**Best by examples**

In [42]:
# We define two arrays
data = np.array([1, 2])
ones = np.ones(2)
# They must be the same shape before performing operation
print("data.shape =", data.shape)
print("ones.shape =", ones.shape)

print("data =\n", repr(data))
print("ones =\n", repr(ones))
# Add them together
c = data + ones
print("c =\n", repr(c))

data.shape = (2,)
ones.shape = (2,)
data =
 array([1, 2])
ones =
 array([1., 1.])
c =
 array([2., 3.])


<img src="./figures/np_array_dataones.png" width="550"/> &nbsp; <img src="./figures/np_data_plus_ones.png" width="550"/>

In [43]:
# Of course, we can do more than just addition!
data = np.array([1, 2])
ones = np.ones(2)
print("data - ones =\n", repr(data - ones))

data - ones =
 array([0., 1.])


In [44]:
data = np.array([1, 2])
ones = np.ones(2)
print("data * ones =\n", repr(data * ones))

data * ones =
 array([1., 2.])


In [45]:
data = np.array([1, 2])
ones = np.ones(2)
print("data / ones =\n", repr(data / ones))

data / ones =
 array([1., 2.])


<img src="./figures/np_sub_mult_divide.png" width="750"/>

### More useful array operations

This section covers **maximum**, **minimum**, **sum**, **mean**, **product**, **standard deviation**. These operations can be achieved by the object methods for the `ndarray` objects:

- `array.max()`
- `array.min()`
- `array.sum()`
- `array.prod()`
- `array.mean()`
- `array.std()`

The function names basically suggest the functionality of the object methods. Clearly, `max`, `min`, `sum` are used to derive the maximum value, the minimum value and the sum of elements in the array `array` by some specific rule. Such specific rule 

In [46]:
a = np.array([1, 2, 3, 4])
print(a.sum(axis=0))

10


In [47]:
# If we start with this array
b = np.array([[1, 1], [2, 2]])
print(b)
# We can sum over the axis of rows with
print("over the axis of rows    -->", b.sum(axis=0))
# or sum over the axis of columns
print("over the axis of columns -->", b.sum(axis=1))

[[1 1]
 [2 2]]
over the axis of rows    --> [3 3]
over the axis of columns --> [2 4]


In [48]:
# Of course, we can sum over the higher dimension
c = np.arange(0, 12).reshape(2, 3, 2)
print("c =\n", c)
print("sum of c over the 3rd axis:\n", c.sum(axis=2))

c =
 [[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]
sum of c over the 3rd axis:
 [[ 1  5  9]
 [13 17 21]]


In [49]:
data = np.array([1, 2, 3])
print("max =", data.max())

print("min =", data.min())

print("sum =", data.sum())

max = 3
min = 1
sum = 6


It’s very common to want to aggregate along a row or column. By default, every NumPy aggregation function will return the aggregate of the entire array. However, as expected we can specify on which axis you want the aggregation function to be computed. For example, you can find the minimum value within each column in a matrix (array of 2 dimensions) by specifying `axis=0`.

In [50]:
a = np.array([[11, 10, 1, 12], [9, 6, 5, 7], [2, 4, 3, 8]])

print("sum =", a.sum())     # sum of all elements in the 2D array

print("min =", a.min())     # minimium of all elements in the 2D array

print("max =", a.max())     # maximum of all elements in the 2D array

sum = 78
min = 1
max = 12


In [51]:
print("a =\n", repr(a))

print("min along the row, within each column -->", a.min(axis=0))

print("min along the column, within each row -->", a.min(axis=1))

a =
 array([[11, 10,  1, 12],
       [ 9,  6,  5,  7],
       [ 2,  4,  3,  8]])
min along the row, within each column --> [2 4 1 7]
min along the column, within each row --> [1 5 2]


### Transposing and reshaping a matrix

This section covers
  - `arr.reshape()`
  - `arr.transpose()`
  - `arr.T`

Very often, we are working with matrices in engineering and mathematical applications. It is common to need to transpose the matrices. NumPy arrays have the property `T` that allows us to transpose a matrix.

<img src="./figures/np_transposing_reshaping.png" width="750"/>


We may also need to switch the dimensions of a matrix. This can happen when, for example, we have a model that expects a certain input shape that is different from our data set. This is where the `reshape()` method can be useful. We simply need to pass in a new dimensions that we want for the matrix.

<img src="./figures/np_reshape.png" width="750"/>

In [52]:
print(a)

for i in range(3):
    print(a[i,:].sum())

[[11 10  1 12]
 [ 9  6  5  7]
 [ 2  4  3  8]]
34
27
17


**Best by examples**

In [53]:
data = np.arange(1, 7)
print("data =", data)
print("data.reshape(2, 3) =\n", data.reshape(2, 3))
print("data.reshape(3, 2) =\n", data.reshape(3, 2))

# The below statement will give error as the total number of elements 
# is only 6 but it wants to reshape data into 3x3 array. Remove comment
# to see the ValueError.
# print("data.reshape(3, 3) =\n", data.reshape(3, 3))

data = [1 2 3 4 5 6]
data.reshape(2, 3) =
 [[1 2 3]
 [4 5 6]]
data.reshape(3, 2) =
 [[1 2]
 [3 4]
 [5 6]]


In [54]:
# We can transpose a matrix
data = np.arange(1, 7)
matrix = data.reshape(2 ,3)
print("matrix =\n", matrix)

# We can use .T
print("matrix.T =\n", matrix.T)
# We can also use .transpose()
print("matrix.transpose()\n", matrix.transpose())


matrix =
 [[1 2 3]
 [4 5 6]]
matrix.T =
 [[1 4]
 [2 5]
 [3 6]]
matrix.transpose()
 [[1 4]
 [2 5]
 [3 6]]


### Reverse an array

NumPy `np.flip()` function allows you to flip, or reverse, the contents of an array along an axis. When using `np.flip()`, specify array you would like to reverse and the axis. If we don't specify the axis, NumPy will reverse the contents along all of the axes of your input array.

**Best by examples**

In [55]:
# Reversing a 1D array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

reversed_arr = np.flip(arr)
print('Reversed Array:', reversed_arr)

Reversed Array: [8 7 6 5 4 3 2 1]


In [56]:
# Reversing a 2D array
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print("Original array\n", arr_2d)

reversed_arr = np.flip(arr_2d)
print("Reversed along both dimensions (rows and column)\n", reversed_arr)

# Reverse the 2D array along the 1st dimension (namely row)
reversed_arr_rows = np.flip(arr_2d, axis=0)
print("Reversed long 1st dimension (row)\n", reversed_arr_rows)

# Reverse the 2D array along the 2nd dimension (namely column)
reversed_arr_columns = np.flip(arr_2d, axis=1)
print("Reversed long 2nd dimension (col)\n", reversed_arr_columns)

Original array
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Reversed along both dimensions (rows and column)
 [[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]
Reversed long 1st dimension (row)
 [[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]
Reversed long 2nd dimension (col)
 [[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]


We can also reverse the contents of only one column or row. For example, you can reverse the contents of the row at index position 1 (the second row). As already explained, the access of NumPy array returns the view copy, thus the change of elements in the array will also affect the original array.

In [57]:
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print("Original array\n", arr_2d)

# We flip the second row of the array arr_2d
arr_2d[1] = np.flip(arr_2d[1])      
print("After flipping the 2nd row\n", arr_2d)

# Then, we can also reverse the column at index position 1 (the second column).
# The ":" appearing in the first dimension means "all elements in the 1st dimension".
# Thus, ":" refers to all the rows.
arr_2d[:,1] = np.flip(arr_2d[:,1])
print("After flipping the 2nd column\n", arr_2d)


Original array
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
After flipping the 2nd row
 [[ 1  2  3  4]
 [ 8  7  6  5]
 [ 9 10 11 12]]
After flipping the 2nd column
 [[ 1 10  3  4]
 [ 8  7  6  5]
 [ 9  2 11 12]]


In [58]:
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

arr_2d.reshape((2,2, 1, 3))

array([[[[ 1,  2,  3]],

        [[ 4,  5,  6]]],


       [[[ 7,  8,  9]],

        [[10, 11, 12]]]])

## Working with mathematical formulas

The ease of implementing mathematical formulas that work on arrays is one of the things that make __NumPy__ so widely used in the scientific Python community.

For example, the mean square error formula (a central formula used in supervised machine learning models that deal with regression):
$$
MSE = \frac{1}{n} \sum\limits_{j=1}^{n} (Y_{j}^{\text{prediction}} - Y_{j}^{\text{data}})^2
$$
Implementing this formula is simple and straightforward in NumPy:

```Python
error = (1/n) * np.sum(np.square(predictions - labels))
```

What makes this work so well is that `predictions` and `labels` can contain one or a thousand values. They only need to be the same size.

We can visualize it this way:

<img src="./figures/np_mse_viz1.png" width="750"/>

In this example, both the predictions and labels vectors contain three values, meaning `n` has a value of three. After we carry out subtractions the values in the vector are squared. Then NumPy sums the values, and your results is the error value for that prediction and a score for the quality of the model.

<img src="./figures/np_mse_viz2.png" width="750"/>

<img src="./figures/np_MSE_explanation2.png" width="750">

### Useful examples

Perhaps, the best way to learn this section is to go through useful examples.

#### **Dot product of two vectors**

In [59]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
# Dot product between vector a and vector b is a number
# This can be done as 
dot_prod = np.sum(a * b)
print("dot product (1st method) =", dot_prod)
# Or we can also write
dot_prod = a.dot(b)
print("dot product (2nd method) =", dot_prod)

dot product (1st method) = 32
dot product (2nd method) = 32


#### **Multiplication of two matrices**

In [60]:
# We can multiply two matrices of appropriate sizes.
A = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
B = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
print("A.shape =", A.shape)
print("B.shape =", B.shape)
# It is clear that we can multiply two matrices A [3 x 4] and B [4 x 2].
C = A.dot(B)
print("C =\n", C)

A.shape = (3, 4)
B.shape = (4, 2)
C =
 [[ 50  60]
 [114 140]
 [178 220]]


#### **Multiplication of one matrix and one vector**

In [61]:
# Let us try to multiply a matrix and a vector
A = np.arange(12).reshape(4, 3)     # matrix A has shape [4 x 3]
b = np.arange(3)                    # vector b has shape (3,)
A_dot_b = A.dot(b)
print("A*b =", A_dot_b)
print("shape of A*b =", A_dot_b.shape)

A*b = [ 5 14 23 32]
shape of A*b = (4,)


We can see that the multiplication returns a vector of shape `(4,)` instead of a column vector of size [4 x 1], or shape `(4, 1)` as we expect in matrix calculation. However, this is perfectly right in the concept of linear algebra. As already explained above, a vector in a mathematical sense contains 4 elements for 4 dimensions and it can be represented as a column vector of shape `(4, 1)` or a row vector of shape `(1, 4)`. If `b` is a column vector, the statement `A.dot(b)` will work out perfectly fine because `A.dot(b)` basically means the normal multiplication between matrices. However, if `b` is represented as a row vector, the statement `A.dot(b)` will raise an error because we cannot multiply a matrix of size [4 x 3] by matrix of size [1 x 4]. In this case, we can still multiply the matrix $\mathbf{A}$ by the transpose of the row vector $\mathbf{b}$ so that the right code would be `A.dot(b.transpose())` or `A.dot(b.T)`.

In [62]:
A = np.arange(12).reshape(4, 3)
b = np.arange(3)
b_col = b[:,np.newaxis]
b_row = b[np.newaxis, :]

# We can multiply A and b_col
A_dot_b = A.dot(b_col)
print("A*b_col =", A_dot_b)
# We cannot multiply A and b_row, but the transpose of b_row works fine
A_dot_b = A.dot(b_row.T)
print("A*b_row =", A_dot_b)
"""The following statement gives error. 
Uncomment the command to see and to learn the error"""
# A.dot(b_row)

A*b_col = [[ 5]
 [14]
 [23]
 [32]]
A*b_row = [[ 5]
 [14]
 [23]
 [32]]


'The following statement gives error. \nUncomment the command to see and to learn the error'

#### **Einstein summation**

Let us assume that we have two matrices of the same size. Let $\mathbf{A}$ and $\mathbf{B}$ are two matrices of the size $[m \times n]$. Then, we want to calculate the following double sum

$$\sigma = \sum\limits_{i=1}^{n} \sum\limits_{j=1}^{n} A_{ij} B_{ij}$$

We call the above multiple sums **Einstein Summation** -- yes, Einstein really refers to this guy

<img src="./figures/einstein.jpg" width=300 >

There are multiple ways to compute the summation $\sigma$ in the above equation with the NumPy library. 

**Method 1** &nbsp; One way is to compute the matrix $\mathbf{C}$ that is obtained by multiplying each of component of $\mathbf{A}$ and $\mathbf{B}$ one by one so that the matrix $\mathbf{C}$ has exactly the same size of $\mathbf{A}$ and $\mathbf{B}$ and is defined by
$$ C_{ij} = A_{ij} B_{ij} \quad \forall i = 1, \ldots, m, j = 1, \ldots, n$$
Then, it is immediately clear that $\sigma$ can be computed as
$$\sigma = \sum\limits_{i=1}^{m} \sum\limits_{j=1}^{n} C_{ij}$$

**Method 2** &nbsp; The second way is to use the function `np.einsum()` provided in the NumPy library. In current case, the following command does the job
```Python
sigma = np.einsum('ij,ij', A, B)
```

In [63]:
A = np.arange(9).reshape(3, 3)
B = np.arange(10, 19, 1).reshape(3, 3)
print(A)
print(B)

C = A * B
print(C.sum())
print("C = ", C)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]
564
C =  [[  0  11  24]
 [ 39  56  75]
 [ 96 119 144]]


In [64]:
A = np.arange(9).reshape(3, 3)
B = np.arange(10, 19, 1).reshape(3, 3)
# First, let us do the first way
A_mult_B = A * B
A_double_dot_B = A_mult_B.sum(axis= (0, 1))
print("1st method:", A_double_dot_B)
np.sum(A * B)
# This can be done by Einstein summation
A_double_dot_B = np.einsum('ij,ij', A, B)
print("2nd method:", A_double_dot_B)

1st method: 564
2nd method: 564


Let $\mathbf{A}$ be a four-dimensional array of size $n_1 \times n_2 \times n_3 \times n_4$ so that each component of $\mathbf{A}$ is represented as $A_{ijkl}$. Let $\mathbf{B}$ be a two-dimensional array of size $n_1 \times n_2$ (effectively a matrix) so that its one component is designated by $B_{ij}$. We want compute a two-dimensional array $\mathbf{C}$ of size $n_3 \times n_4$ according to the definition
$$ C_{kl} = \sum\limits_{i=1}^{n_1} \sum_{j=1}^{n_2} A_{ijkl} \, B_{ij} \quad \forall k = 1, \ldots, n_3, l = 1, \ldots n_4$$

That is, if we fix one pair of values for $k$ and $l$, we need to perform double summations over the running indices $i$ and $j$ to compute just one component $C_{kl}$. Following that, we need to compute $n_3 \cdot n_4$ times the double summations, namely 
$$\sum\limits_{i=1}^{n_1}\sum\limits_{j=1}^{n_2}$$ 
to retrieve all the components of the matrix $\mathbf{C}$.

Again, we can compute all of the components of $\mathbf{C}$ in multiple ways. The first method is to fix $k = k_0$ and $l = l_0$ and pretend that $A_{ijk_0 l_0}$ for $i$ and $j$ running as a matrix and then compute the double summation just as the double summations for two matrices presented in the above example. Then, we let $k_0$ and $l_0$ run accordingly to obtain all the components $C_{kl}$. In this way, we essentially repeat the above examples but in two loops corresponding the index $k$ and $l$.

The second method is rather simple and thank to the `np.einsum()` function in NumPy library. Let `A` and `B` be the variables corresponding to the four-dimensional array and the two-dimensional array described above. Then, the following command does the job

```Python
C = np.einsum('ijkl,ij -> kl', A, B)
```

In [65]:
A = np.arange(3 * 3 * 3 * 3).reshape(3, 3, 3, 3)
B = np.arange(3 * 3).reshape(3, 3)

C = np.einsum('ijkl,ij -> kl', A, B)
print("1st method:\n", C)

# Of course we can do the more elaborate, understandable but less efficient way.
C = np.empty((3, 3))            # reuse the variable name to define a new object
for k in range(3):
    for l in range(3):
        AA = A[:,:,k,l]
        matrix = AA * B
        C[k,l] = matrix.sum(axis=(0, 1))
        
print("2nd method:\n", C)

# The 3rd method is less understandable than the 2nd way

1st method:
 [[1836 1872 1908]
 [1944 1980 2016]
 [2052 2088 2124]]
2nd method:
 [[1836. 1872. 1908.]
 [1944. 1980. 2016.]
 [2052. 2088. 2124.]]


In [66]:
A = np.arange(3 * 3 * 3 * 3).reshape(3, 3, 3, 3)
B = np.arange(3 * 3).reshape(3, 3)

C = B[:, :, np.newaxis, np.newaxis]
C.shape

(3, 3, 1, 1)

In [67]:
AC = A * C
AC.shape
AC.sum(axis=(0, 1))

array([[1836, 1872, 1908],
       [1944, 1980, 2016],
       [2052, 2088, 2124]])